# Homework assignment #2 - NumPy
Name: Paul Clarke


ID: PM1800448

### Import NumPy Package

In [1]:
# import numpy package
import numpy as np

### 1. Basic Data Statistics

####  Create an array of 5 zeros

In [16]:
five_zeros = np.zeros(5)

In [17]:
five_zeros

array([0., 0., 0., 0., 0.])

#### Use this array to create an array of 10 fives

In [4]:
five_fives = five_zeros + 5

In [9]:
ten_fives = np.hstack([five_fives, five_fives])
ten_fives

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Creat the matrix bellow. The code must not use the same function more then one time in one run
 

In [18]:
matrix = np.zeros([5,5]) + np.arange(5)
matrix

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### Create a 8x8 matrix and fill it with a checkerboard pattern with 0 zeros and ones.

In [88]:
checkerboard = np.zeros([8,8])

In [89]:
checkerboard

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [90]:
# slow way
for i in range(len(checkerboard)):
 for j in range(len(checkerboard[i])):
  if (i%2!=0 and j%2==0) or (i%2==0 and j%2!=0):
   checkerboard[i][j] = 1

checkerboard

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [91]:
# I did not think of this myself, it was provided to me by a talented masters student, Dina Khasanova. The one I thought of is above
# fast way
checkerboard[::2, 1::2] = 1
checkerboard[1::2, ::2] = 1

checkerboard


array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### Create an array of 20 linearly spaced points between 0 and 1:

In [43]:
linspace = np.linspace(0,1)

In [44]:
linspace

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

# Working with data:

# Daily Rate of Growth of new COVID19 Cases in Israel

Read the header row (first row) of file 'covid19_israel.csv', and print the header.  

In [57]:
header = np.loadtxt(r"COVID19_Israel.csv", delimiter=",", dtype='str')[0]
print(header)


['ObservationDate' 'New Confirmed' 'New Deaths' 'New Recovered']


Read columns 2, 3, 4 (indices 1, 2, 3) of file "covid19_israel.csv" into **new_cases** variable.  
Use **delimiter** parameter to indicate comma separated values.  
Use **skiprows** parameter to skip the first header row.  
Use **usecols** parameter to read the columns 2, 3, 4 (indices 1, 2, 3).    
Print the last 5 rows.

In [61]:
new_cases = np.loadtxt(r"COVID19_Israel.csv", delimiter=",", dtype='int', skiprows=1, usecols=[1,2,3])
print(new_cases[-5:])

[[342   4  11]
 [584   0  10]
 [628   3  43]
 [448   1  29]
 [663   4  63]]


Print the date of the day were the most patients verified.

In [63]:
dates = np.loadtxt(r"COVID19_Israel.csv", delimiter=",", dtype='str', skiprows=1, usecols=0)

array(['2/21/2020', '2/22/2020', '2/23/2020', '2/24/2020', '2/25/2020',
       '2/26/2020', '2/27/2020', '2/28/2020', '2/29/2020', '3/1/2020',
       '3/2/2020', '3/3/2020', '3/4/2020', '3/5/2020', '3/6/2020',
       '3/7/2020', '3/8/2020', '3/9/2020', '3/10/2020', '3/11/2020',
       '3/12/2020', '3/13/2020', '3/14/2020', '3/15/2020', '3/16/2020',
       '3/17/2020', '3/18/2020', '3/19/2020', '3/20/2020', '3/21/2020',
       '3/22/2020', '3/23/2020', '3/24/2020', '3/25/2020', '3/26/2020',
       '3/27/2020', '3/28/2020', '3/29/2020', '3/30/2020', '3/31/2020'],
      dtype='<U9')

In [66]:
print(dates[np.argmax(new_cases[:,0])])

3/31/2020


Calculate the total daily number of confirmed caases, death cases, and recovered cases using numpy's **cumsum** function.  
Use the correct **axis** parameter to sum across rows.  
Print the total daily number of confirmed cases, death cases, and recovered cases at the last measured date 31/3/2020 on the last row.   

In [74]:
cum_total_arr = np.cumsum(new_cases, axis=0)

In [75]:
print(cum_total_arr[-1])

[5358   20  224]


Calculate the increase in the number of verified cases for each day:<br>
New Confirmed - (New Deaths + New Recovered)<br>
 to new numpy array.

In [76]:
verified_increase = new_cases[:,0] - (new_cases[:, 1] + new_cases[:,2])

In [77]:
verified_increase

array([  1,   0,   0,   0,   0,   1,   0,   1,   3,   3,   0,   2,   3,
         1,   4,   0,  18,   0,  17,  51,  22,  30,  32,  58,   4,  75,
        96, 244,  25, 155, 187, 367, 474, 432, 311, 327, 574, 582, 418,
       596])

In [16]:
# I don't use float here as we're talking about people

array([  1.,   0.,   0.,   0.,   0.,   1.,   0.,   1.,   3.,   3.,   0.,
         2.,   3.,   1.,   4.,   0.,  18.,   0.,  17.,  51.,  22.,  30.,
        32.,  58.,   4.,  75.,  96., 244.,  25., 155., 187., 367., 474.,
       432., 311., 327., 574., 582., 418., 596.])

Draw a random row from the table and print it.

In [78]:
np.random.seed(42)

In [80]:
random_row = np.loadtxt(r"COVID19_Israel.csv", delimiter=",", dtype='str', skiprows=1)[np.random.randint(0,dates.shape[0])]

In [81]:
random_row

array(['3/30/2020', '448', '1', '29'], dtype='<U9')