In [9]:
import math as m
import numpy as np

In [3]:
raw_values = [n for n in range(-10,11)]

In [7]:
pi_operation = [raw_values[i]*m.pi/10 for i in range(len(raw_values))]
print(pi_operation)

[-3.141592653589793, -2.827433388230814, -2.5132741228718345, -2.199114857512855, -1.8849555921538759, -1.5707963267948966, -1.2566370614359172, -0.9424777960769379, -0.6283185307179586, -0.3141592653589793, 0.0, 0.3141592653589793, 0.6283185307179586, 0.9424777960769379, 1.2566370614359172, 1.5707963267948966, 1.8849555921538759, 2.199114857512855, 2.5132741228718345, 2.827433388230814, 3.141592653589793]


In [44]:
a = np.array((1.0,2.0,3.0,4.0))

In [40]:
type(a)

numpy.ndarray

In [45]:
a.dtype

dtype('float64')

In [11]:
print(a)

[1. 2. 3. 4.]


In [35]:
lst = [[1,2,3, 4],[4,5,6, 7]]

mat = np.array(lst, float)

In [38]:
mat

array([[1., 2., 3., 4.],
       [4., 5., 6., 7.]])

In [46]:
zeros = np.zeros((4,6), float)
zeros

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [47]:
ones = np.ones((2,4))
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [52]:
empty = np.empty((2,4))
empty

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])