In [46]:
import numpy as np
import math
row_col = np.array([[12,5,2,4],[7,6,8,8],[1,6,7,7]])

In [3]:
row_col

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [4]:
row_col[:2,:3]

array([[12,  5,  2],
       [ 7,  6,  8]])

In [5]:
row_col[:3, ::2]

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

In [6]:
row_col[::-1, ::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

In [8]:
row_col[::2,::3]

array([[12,  4],
       [ 1,  7]])

In [11]:
row_col[np.arange(3), np.arange(3)]

array([12,  6,  7])

In [13]:
a = np.arange(10)

In [14]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
d = a[1:4]

In [16]:
d

array([1, 2, 3])

In [17]:
d[0]

1

In [25]:
mat = np.arange(1,10).reshape(3,3)
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
mat.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
mat.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [31]:
row_1 = np.array([1,2,3])
row_2 = np.array([4,5,6])

big_row = np.hstack([row_1,row_2])
matrix = np.vstack([row_1,row_2])
print(big_row)
print(matrix)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [32]:
row_col_1 = np.array([[1,2,3],[4,5,6]])
row_col_2 = np.array([[7,8,9], [10,11,12]])

np.concatenate((row_col_1, row_col_2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [33]:
np.concatenate((row_col_1, row_col_2), axis=1)


array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [34]:
mat1 = np.array([[1,2,3],[4,5,6]])

In [43]:
split = np.split(mat1,2,axis=0)

In [44]:
split

[array([[1, 2, 3]]), array([[4, 5, 6]])]

In [47]:
a = np.linspace(-math.pi, math.pi,8)

In [48]:
a

array([-3.14159265, -2.24399475, -1.34639685, -0.44879895,  0.44879895,
        1.34639685,  2.24399475,  3.14159265])

In [49]:
np.sin(a)

array([-1.22464680e-16, -7.81831482e-01, -9.74927912e-01, -4.33883739e-01,
        4.33883739e-01,  9.74927912e-01,  7.81831482e-01,  1.22464680e-16])

In [50]:
x = np.array([[5,0,3,3],[7,9,3,5],[2,4,7,6]])

In [51]:
x<6

array([[ True,  True,  True,  True],
       [False, False,  True,  True],
       [ True,  True, False, False]])

In [52]:
np.count_nonzero(x<6) # True = 1, False = 0

8

In [55]:
np.sum(x < 6)

8

In [64]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [60]:
np.savetxt("test.txt", x)

In [58]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [67]:
np.savetxt("test2.txt",x,fmt="%2.3f",delimiter=" :-) ")

In [69]:
np.loadtxt("test2.txt", x, delimiter=" :-) ", usecols=(0,2))

TypeError: Cannot construct a dtype from an array